version: '3'

services:
  # Zookeeper setup
  # zookeeper:
  #   image: confluentinc/cp-zookeeper:7.5.0
  #   ports:
  #     - "2181:2181"
  #   environment:
  #     ZOOKEEPER_CLIENT_PORT: 2181

  # # Kafka setup
  # kafka:
  #   image: confluentinc/cp-kafka:7.5.0
  #   ports:
  #     - "9092:9092"
  #   environment:
  #     KAFKA_BROKER_ID: 1
  #     KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
  #     KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
  #     KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
  #     KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
  #   depends_on:
  #     - zookeeper

  # Redis setup
  redis:
    image: docker.dragonflydb.io/dragonflydb/dragonfly
    container_name: redis
    ulimits:
      memlock: -1
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  # MySQL setup
  mysql:
    image: mysql:8.0
    container_name: my-mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: eren139
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: eren139
    volumes:
      - mysqldata:/var/lib/mysql

volumes:
  redis_data:
  mysqldata:
